// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAutoStart() {
  return window['go']['main']['App']['CheckAutoStart']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetClipboardHistory() {
  return window['go']['main']['App']['GetClipboardHistory']();
}

export function GetClipboardImage() {
  return window['go']['main']['App']['GetClipboardImage']();
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetClipboardContent(arg1) {
  return window['go']['main']['App']['SetClipboardContent'](arg1);
}

export function SetClipboardImage(arg1) {
  return window['go']['main']['App']['SetClipboardImage'](arg1);
}

export function SetClipboardText(arg1) {
  return window['go']['main']['App']['SetClipboardText'](arg1);
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}
