// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAutoStart():Promise<boolean>;

export function ClearHistory():Promise<void>;

export function GetClipboardHistory():Promise<Array<main.ClipboardItem>>;

export function GetClipboardImage():Promise<string>;

export function GetClipboardText():Promise<string>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetClipboardContent(arg1:string):Promise<void>;

export function SetClipboardImage(arg1:string):Promise<void>;

export function SetClipboardText(arg1:string):Promise<void>;

export function WindowHide():Promise<void>;

export function WindowShow():Promise<void>;
